homeassistant:
  
  name: Casa
  latitude: !secret latitude_casa
  longitude: !secret longitude_casa
#  elevation: !secret elevation
  elevation: 698
  unit_system: metric
  time_zone: UTC
 
#  auth_providers:
#   - type: homeassistant

mqtt:
  discovery: true
  broker: localhost
  port: !secret port_mqtt
  client_id: casa
  username: !secret username_mqtt
  password: !secret password_mqtt
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

############################
#INTEGRACIONES
############################

shopping_list:

breaking_changes:

spotify:
  client_id: !secret spotify_clientID
  client_secret: !secret spotify_secret

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 9620182

shell_command:
  renovar_certificado_ssl: '/bin/bash /home/homeassistant/scripts/renovar_certificado.sh'

webhook:

zigbee2mqtt_networkmap:
  topic: Casa

panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/community/zigbee2mqtt_networkmap/map.html?engine=circo'
    icon: 'mdi:graphql'

#lovelace:
#  mode: yaml

###############################################
# TIMERS
###############################################

timer:
  cocina:
    duration: '00:03:00'
  ambientador:
    duration: '00:20:00'
  dormitorio: 
    duration: '00:05:00'
    

###############################################
# MANTENIMIENTO Y OTROS PLUGINGS
###############################################

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url

duckdns:
  domain: !secret https_domain
  access_token: !secret duckdns_access_token

logger:
  default: ERROR
#  logs:
#    homeassistant.components.automation: debug
#    urllib3.connectionpool: critical
#    homeassistant.components.mqtt: info
#    homeassistant.components.bluetooth_le_tracker: debug

frontend:
  themes: !include_dir_merge_named themes

config:
discovery:
system_health:
mobile_app:

notify:
  - name: Home_Assistant
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret notification_sender
    encryption: starttls
#    starttls: true
    username: !secret notification_username
    password: !secret notification_password
    recipient: !secret notification_recipient_jairo
    sender_name: Leak Alert

var:
  home_mode:
    friendly_name: home_mode
    initial_value: casa


# Enables support for tracking state changes over time
history:
  include:
    domains:
#      - automation
      - switch
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - binary_sensor.0x00158d00035c6967_contact
      - binary_sensor.puerta_terraza_contact
      - binary_sensor.0x00158d0003031c6b_contact
      - switch.bf5f971cf225cffafaiye7
      - switch.luz_salon_mss310_main_channel
      - switch.home_cinema_mss310_main_channel
      - switch.bf74042d28e39f1d19joll
      - switch.lampara_habitacion_principal
      - switch.luz_cocina
      - sensor.0x00158d0004446062_temperature
      - sensor.0x00158d0004446062_temperature
# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

alexa:
  smart_home:

#recorder:
#  purge_keep_days: 7
#  purge_interval: 1
#  exclude:
#    domains:
#      - media_player
#      - device_tracker

#influxdb:
#  host: !secret influxdb_host
#  port: !secret influxdb_port
#  username: !secret influxdb_username
#  password: !secret influxdb_password
#  database: !secret influxdb_database
#  max_retries: 3
#  default_measurement: state

#trakt:
#  client_id: 25e0f255271ded36462713101eddf7e48fe60770d69592b91dd2e243872f287d
#  client_secret: 610e2850e8e523f976ae3956f53e58d385967e3490e4206ef8068203c3f2cac8

input_select:
  themes:
    name: 'Themes'
    icon: mdi:format-paint
    options:
      - Caule Black Rose
      - Caule Black Purple
      - Caule Black Blue 
      - Caule Black Aqua
      - Caule Black Green
      - Caule Black Yellow
      - Caule Black Orange
      - Caule Black Coral
      - Caule Black Pink
      - Caule Black Gray
      - Caule Dark Rose
      - Caule Dark Purple
      - Caule Dark Blue 
      - Caule Dark Aqua
      - Caule Dark Green
      - Caule Dark Yellow
      - Caule Dark Orange
      - Caule Dark Coral
      - Caule Dark Pink
      - Caule Dark Gray
      - Caule Light Rose
      - Caule Light Purple
      - Caule Light Blue 
      - Caule Light Aqua
      - Caule Light Green
      - Caule Light Yellow
      - Caule Light Orange
      - Caule Light Coral
      - Caule Light Pink
      - Caule Light Gray
      - Caule Black Rose Glass
      - Caule Black Purple Glass
      - Caule Black Blue Glass 
      - Caule Black Aqua Glass
      - Caule Black Green Glass
      - Caule Black Yellow Glass
      - Caule Black Orange Glass
      - Caule Black Coral Glass
      - Caule Black Pink Glass
      - Caule Black Gray Glass      
      - default

###################################################
##### SUBDIRECTORIOS
###################################################

sensor:     !include sensor.yaml
automation: !include automations.yaml
zone: !include zone.yaml
device_tracker: !include device_tracker.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
group: !include groups.yaml

# group: !include_dir_merge_named groups
# customize: !include customize.yaml
#panel_iframe: !include panels.yaml
